blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/kiranojhanp/fullstack-typescript-turborepo-starter/discussions
    about: Ask questions and discuss topics with other community members
